export const allItems = [
    { _id: 1, title: "All Departments" },
    { _id: 2, title: "Arts & Crafts" },
    { _id: 3, title: "Automotive" },
    { _id: 4, title: "Baby" },
    { _id: 5, title: "Beauty & Personal Care" },
    { _id: 6, title: "Books" },
    { _id: 7, title: "Boys' Fashion" },
    { _id: 8, title: "Computers" },
    { _id: 9, title: "Deals" },
    { _id: 10, title: "Digital Music" },
    { _id: 11, title: "Electronics" },
    { _id: 12, title: "Girls' Fashion" },
    { _id: 13, title: "Health & Household" },
    { _id: 14, title: "Home & Kitchen" },
    { _id: 15, title: "Industrial & Scientific" },
    { _id: 16, title: "Kindle Store" },
    { _id: 17, title: "Luggage" },
    { _id: 18, title: "Men's Fashion" },
    { _id: 19, title: "Movies & TV" },
    { _id: 20, title: "Music, CDs & Vinyl" },
    { _id: 21, title: "Pet Supplies" },
    { _id: 22, title: "Prime Video" },
    { _id: 23, title: "Software" },
    { _id: 24, title: "Sports & Outdoors" },
    { _id: 25, title: "Tools & Home Improvement" },
    { _id: 26, title: "Toys & Games" },
    { _id: 27, title: "Video Games" },
    { _id: 28, title: "Women's Fashion" },
  ];